apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-capture-portfolio
  labels:
    app: react-capture-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-capture-portfolio
  template:
    metadata:
      labels:
        app: react-capture-portfolio
    spec:
      containers:
        - name: react-capture-portfolio
          image: docker.io/hauze/react-capture-portfolio:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: capture-portfolio-service
spec:
  selector:
    app: react-capture-portfolio
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
